name: Comment on First-Time Contributor PR

on:
  workflow_call:
    inputs:
      comment-body:
        description: "Comment to post on first PR"
        required: false
        type: string
        default: |
          ðŸ‘‹ Hi @${{ github.actor }}!

permissions:
  pull-requests: write
  contents: read

jobs:
  first-pr-comment:
    runs-on: ubuntu-latest

    steps:
      # - name: Check if contributor has merged PRs before
      #   id: check
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       const owner = context.repo.owner;
      #       const repo = context.repo.repo;
      #       const author = context.payload.pull_request.user.login;

      #       const { data } = await github.rest.search.issuesAndPullRequests({
      #         q: `repo:${owner}/${repo} is:pr is:merged author:${author}`
      #       });

      #       core.setOutput("merged_count", data.total_count);


      - name: Comment on first PR
        if: steps.check.outputs.merged_count == '0'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `${{ inputs.comment-body }}`
            });